backend/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('currency.urls'))
]

backend/currency/urls.py
from django.urls import path

from . import views

app_name = "currency"

urlpatterns = [path("", views.CurrencyView.as_view(), name="currency_form"),
               path("currencies/", views.CurrencyAPI.as_view(), name="currencies")
               ]

backend/currency/models.py
from django.db import models


class CurrencyName(models.Model):
    name = models.CharField(max_length=35)
    code = models.CharField(max_length=3)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = "Currency name"
        verbose_name_plural = "Currency Names"


class CurrencyDate(models.Model):
    date = models.DateField(db_index=True, unique=True)

    def __str__(self):
        return str(self.date)

    class Meta:
        verbose_name = "Currency Date"
        verbose_name_plural = "Currency Dates"


class CurrencyValue(models.Model):
    exchange_rate = models.DecimalField(max_digits=10, decimal_places=8)
    currency_name = models.ForeignKey("CurrencyName", on_delete=models.CASCADE, related_name="currency_values")
    currency_date = models.ForeignKey("CurrencyDate", on_delete=models.CASCADE, related_name="currency_values")

    def __str__(self):
        return str(self.exchange_rate)

    class Meta:
        verbose_name = "Currency Value"
        verbose_name_plural = "Currency Values"
        unique_together = ("currency_name", "currency_date")

backend/users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

backend/currency/forms.py
from django import forms


class CurrencyForm(forms.Form):
    start_date = forms.DateField(widget=forms.TextInput(attrs={"type": "date"}))
    end_date = forms.DateField(widget=forms.TextInput(attrs={"type": "date"}))
    currency = forms.MultipleChoiceField(choices=[], widget=forms.CheckboxSelectMultiple)

backend/currency/views.py
import json
from datetime import datetime, timedelta
from urllib import request

from django.views.generic import FormView
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from . import forms, models
from .models import CurrencyValue
from .serializers import CurrencyRateSerializer


def get_holidays(start_date, end_date):
    start_date = datetime.strftime(start_date, "%Y-%m-%d")
    end_date = datetime.strftime(end_date, "%Y-%m-%d")
    url = f"https://openholidaysapi.org/PublicHolidays?countryIsoCode=PL&languageIsoCode=PL&validFrom={start_date}&validTo={end_date}"
    with request.urlopen(url) as response:
        data = json.loads(response.read().decode())

    return [holiday["startDate"] for holiday in data]


def count_holidays_during_weekdays(start_date, end_date):
    holidays = get_holidays(start_date, end_date)

    week_days_counter = 0
    for holiday in holidays:
        if datetime.strptime(holiday, "%Y-%m-%d").weekday() < 5:
            week_days_counter += 1

    return week_days_counter


def count_days_off(start_date, end_date):
    days_count = 0

    while start_date <= end_date:
        if start_date.weekday() >= 5:
            days_count += 1

        start_date += timedelta(days=1)

    return days_count


def count_days(start_date, end_date):
    return (end_date - start_date).days


def get_currency_data_from_nbp_API(start_date, end_date):
    url = f"http://api.nbp.pl/api/exchangerates/tables/a/{start_date}/{end_date}/"

    with request.urlopen(url) as response:
        data = json.loads(response.read().decode())

    currency_names = models.CurrencyName.objects.all()

    for day in data:
        if not models.CurrencyDate.objects.filter(date=datetime.strptime(day["effectiveDate"], "%Y-%m-%d")):
            currency_date = models.CurrencyDate.objects.create(date=datetime.strptime(day["effectiveDate"], "%Y-%m-%d"))

            currency_values = [
                models.CurrencyValue(
                    exchange_rate=rate["mid"],
                    currency_date=currency_date,
                    currency_name=currency_names.get(code=rate["code"]),
                )
                for rate in day["rates"]
            ]
            models.CurrencyValue.objects.bulk_create(currency_values)


class CurrencyView(FormView):
    form_class = forms.CurrencyForm
    template_name = "currency/currency_view.html"
    success_url = "/"

    def get_form(self, form_class=None):
        currencies = models.CurrencyName.objects.all()
        form = super().get_form(form_class)

        form.fields["currency"].choices = [(currency.code, currency.name.title()) for currency in currencies]

        return form


class CurrencyAPI(APIView):
    def post(self, request, format=None):
        start_date = request.data.get("start_date")
        end_date = request.data.get("end_date")

        if start_date is not None and end_date is not None:
            start_date = datetime.strptime(start_date, "%Y-%m-%d").date()
            end_date = datetime.strptime(end_date, "%Y-%m-%d").date()
            currencies = models.CurrencyName.objects.all()

            dates = models.CurrencyDate.objects.filter(date__range=(start_date, end_date))

            if dates.count() < count_days(start_date, end_date) - count_holidays_during_weekdays(
                start_date, end_date
            ) - count_days_off(start_date, end_date):
                get_currency_data_from_nbp_API(start_date, end_date)

            currency_data = models.CurrencyValue.objects.filter(
                currency_date__date__range=(start_date, end_date)
            ).select_related("currency_name")

            data = {
                "labels": [date.date.strftime("%Y-%m-%d") for date in dates],
                "datasets": [
                    {
                        "label": currency.code,
                        "data": [
                            float(value.exchange_rate)
                            for value in currency_data
                            if value.currency_name.code == currency.code
                        ],
                    }
                    for currency in currencies
                ],
            }

        else:
            return Response("Start date and End date reguired.", status=status.HTTP_400_BAD_REQUEST)

        return Response(data, status=status.HTTP_200_OK)

backend/currency/templates/currency/currency_view.html
<!--{% load escape_js_code %}-->
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

</head>
<body>
<form action="" method="POST" id="currencyForm">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Submit</button>
</form>
<div style="width: 800px;">
    <canvas id="currencyChart"></canvas>
</div>
<!--<pre>-->


<!--    {% for day in dates %}-->

<!--    {{ day.exchange_rate }} - {{ day.currency_name.name }} - {{ day.currency_date.date }}-->

<!--    {% endfor %}-->
<!--</pre>-->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    (async function () {
        const form = document.querySelector('#currencyForm');
        const chartElement = document.getElementById('currencyChart');
        const startDateInput = document.querySelector('input#id_start_date');
        const endDateInput = document.querySelector('input#id_end_date');
        const checkboxes = document.querySelectorAll('input[name="currency"]');
        let chart;
        let names = []

        form.addEventListener('submit', async (event) => {
            event.preventDefault();

            const response = await fetch('/currencies/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    start_date: startDateInput.value,
                    end_date: endDateInput.value,
                }),
            });

            const data = await response.json();

            if (chart) {
                chart.destroy(); // Usuń poprzedni wykres, jeśli istnieje
            }


            checkboxes.forEach((checkbox) => {
                checkbox.addEventListener('change', () => {
                    if (checkbox.checked) {
                        names.push(checkbox.value)
                        console.log('Zaznaczono:', checkbox.value);
                        // Tutaj możesz wykonać dowolne działania związane z zaznaczeniem checkboxa
                    } else {
                        names = names.filter((name) => name !== checkbox.value)
                        console.log('Odznaczono:', checkbox.value);
                        // Tutaj możesz wykonać dowolne działania związane z odznaczeniem checkboxa
                    }
                });
            });
            console.log(names)
            console.log(data)
            console.log(data.datasets.filter((dt) => names.includes(dt.label)))
            const dataFiltered = {...data, datasets: data.datasets.filter((dt) => names.includes(dt.label))}
            chart = new Chart(chartElement, {
                type: 'line',
                data: dataFiltered,
                options: {
                    responsive: true,
                    plugins: {
                        legend: {
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'currency rate',
                        },
                    },
                    scales: {
                        y: {
                            min: 0,
                            max: 10,
                            ticks: {
                                stepSize: 0.01,
                            },
                        },
                    },
                },
            });
        });
    })();
</script>

</body>
</html>